#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
validate_submission.py - 申报材料最终校验脚本 v1.1.0

对已打包输出的 _最终申报包/ 目录进行7维校验：
  1. 完整性 — 19类是否齐全，每类文件是否存在
  2. 命名 — 文件名是否符合规范
  3. 大小 — 每文件是否 ≤ 申报系统上限
  4. 格式 — PDF是否未加密、可正常打开
  5. OCR可读 — 扫描件是否有可读文本层
  6. 内容一致性 — OCR提取关键词匹配预期
  7. AI水印 — 内容不得包含AI生成水印字样（v1.1.0新增）

CLI 用法:
    python validate_submission.py --output-dir "_最终申报包/"
    python validate_submission.py --output-dir "_最终申报包/" --requirements "99.其他资料/资料要求.xlsx"
"""

import argparse
import json
import os
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path

COMMON_DIR = Path(__file__).parent

CATEGORY_DIR_NAMES = {
    1: "01_知识产权证明材料", 2: "02_企业研究开发活动情况证明材料",
    3: "03_上年度高新技术产品（服务）证明材料", 4: "04_科技成果转化情况证明材料",
    5: "05_国家或行业标准制定情况证明材料", 6: "06_营业执照",
    7: "07_申报书封皮", 8: "08_近三年财务审计报告",
    9: "09_近三年企业所得税纳税申报表", 10: "10_近三年研发费用专项审计报告",
    11: "11_近一年高新产品收入专项审计报告", 12: "12_研发组织管理制度及辅助账",
    13: "13_研发机构设立及产学研合作证明材料", 14: "14_科技成果转化激励制度及双创平台",
    15: "15_科技人员培养引进及绩效奖励制度", 16: "16_人力资源情况证明材料",
    17: "17_上年度代表性销售合同与发票", 18: "18_企业承诺书",
    19: "19_打印申请书签字盖章扫描件",
}

CATEGORY_NAMES = {
    1: "知识产权证明材料", 2: "企业研究开发活动情况证明材料",
    3: "上年度高新技术产品（服务）证明材料", 4: "科技成果转化情况证明材料",
    5: "国家或行业标准制定情况证明材料", 6: "营业执照",
    7: "申报书封皮", 8: "近三年财务审计报告",
    9: "近三年企业所得税纳税申报表", 10: "近三年研发费用专项审计报告",
    11: "近一年高新技术产品（服务）收入专项审计报告", 12: "研发组织管理制度、研发投入核算、辅助账",
    13: "研发机构设立及产学研合作证明材料", 14: "科技成果转化激励制度及双创平台",
    15: "科技人员培养引进及绩效奖励制度", 16: "人力资源情况证明材料",
    17: "上年度代表性销售合同与发票", 18: "企业承诺书",
    19: "打印申请书签字盖章扫描件",
}

CATEGORY_RULES = {
    1: {"allowed_formats": [".pdf"], "size_limit_mb": 2, "name_patterns": [re.compile(r"^IP\d{2}_.+\.pdf$", re.IGNORECASE)]},
    2: {"allowed_formats": [".pdf"], "size_limit_mb": 2, "name_patterns": [re.compile(r"^RD\d{2}_.+\.pdf$", re.IGNORECASE)]},
    3: {"allowed_formats": [".pdf"], "size_limit_mb": 4, "name_patterns": [re.compile(r"^PS\d{2}_.+\.pdf$", re.IGNORECASE)]},
    4: {"allowed_formats": [".pdf"], "size_limit_mb": 2, "name_patterns": [re.compile(r"^\d{2}_.+\.pdf$")]},
    5: {"allowed_formats": [".pdf"], "size_limit_mb": 2, "name_patterns": [re.compile(r"^\d{2}_.+\.pdf$")]},
    6: {"allowed_formats": [".jpg", ".jpeg", ".png"], "size_limit_mb": 0.5, "name_patterns": [re.compile(r"^营业执照\.(jpg|jpeg|png)$")]},
    7: {"allowed_formats": [".pdf"], "size_limit_mb": 1, "name_patterns": [re.compile(r"^申报书封皮\.pdf$")]},
    8: {"allowed_formats": [".pdf"], "size_limit_mb": 100, "name_patterns": [re.compile(r"^\d{4}_财务审计报告\.pdf$")]},
    9: {"allowed_formats": [".pdf"], "size_limit_mb": 5, "name_patterns": [re.compile(r"^\d{4}_企业所得税纳税申报表\.pdf$")]},
    10: {"allowed_formats": [".pdf"], "size_limit_mb": 100, "name_patterns": [re.compile(r"^研发费用专项审计报告\.pdf$")]},
    11: {"allowed_formats": [".pdf"], "size_limit_mb": 100, "name_patterns": [re.compile(r"^高新产品收入专项审计报告\.pdf$")]},
    12: {"allowed_formats": [".pdf"], "size_limit_mb": 20, "name_patterns": [re.compile(r"^研发组织管理制度及辅助账\.pdf$")]},
    13: {"allowed_formats": [".pdf"], "size_limit_mb": 20, "name_patterns": [re.compile(r"^研发机构设立及产学研合作证明材料\.pdf$")]},
    14: {"allowed_formats": [".pdf"], "size_limit_mb": 5, "name_patterns": [re.compile(r"^科技成果转化激励制度及双创平台\.pdf$")]},
    15: {"allowed_formats": [".pdf"], "size_limit_mb": 5, "name_patterns": [re.compile(r"^科技人员培养引进及绩效奖励制度\.pdf$")]},
    16: {"allowed_formats": [".pdf"], "size_limit_mb": 8, "name_patterns": [re.compile(r"^人力资源情况证明材料\.pdf$")]},
    17: {"allowed_formats": [".pdf"], "size_limit_mb": 20, "name_patterns": [re.compile(r"^上年度代表性销售合同与发票\.pdf$")]},
    18: {"allowed_formats": [".pdf"], "size_limit_mb": 1, "name_patterns": [re.compile(r"^企业承诺书\.pdf$")]},
    19: {"allowed_formats": [".pdf"], "size_limit_mb": 50, "name_patterns": [re.compile(r"^打印申请书签字盖章扫描件\.pdf$")]},
}

AI_WATERMARK_PATTERNS = [
    re.compile(r"AI.{0,5}(生成|撰写|辅助|创作|编写)", re.IGNORECASE),
    re.compile(r"(AI生成|AI辅助|AI撰写|AI创作|AI编写)", re.IGNORECASE),
    re.compile(r"(自动生成|由.{0,10}(脚本|程序|工具).{0,5}生成)", re.IGNORECASE),
    re.compile(r"(Generated by|Powered by|Created by)\s*(AI|Claude|GPT|TRAE|Copilot|DeepSeek)", re.IGNORECASE),
    re.compile(r"(报告|材料|文档|内容).{0,10}由.{0,10}(AI|人工智能|大模型|LLM)", re.IGNORECASE),
    re.compile(r"(本(报告|材料|文档).{0,10}(自动|AI|人工智能).{0,10}(生成|创建))", re.IGNORECASE),
    re.compile(r"(AI watermark|AI水印|AI标识)", re.IGNORECASE),
    re.compile(r"TRAE.{0,5}(生成|辅助|IDE)", re.IGNORECASE),
    re.compile(r"Claude.{0,5}(生成|辅助|AI)", re.IGNORECASE),
    re.compile(r"ChatGPT|GPT-\d|OpenAI", re.IGNORECASE),
    re.compile(r"(由|通过).{0,10}(大语言模型|大模型|LLM).{0,10}(生成|撰写)", re.IGNORECASE),
    re.compile(r"(model|模型).{0,10}(生成|标识|水印|署名)", re.IGNORECASE),
]

EXPECTED_KEYWORDS = {
    1: ["专利", "知识产权", "证书", "登记"], 2: ["研发", "立项", "项目", "技术"],
    3: ["产品", "技术", "指标", "检测"], 4: ["成果", "转化", "应用", "合同"],
    5: ["标准", "规范", "行业"], 6: ["营业执照", "统一社会信用代码"],
    7: ["高新技术企业", "认定", "申请书"], 8: ["审计", "财务报表", "注册会计师"],
    9: ["企业所得税", "纳税", "申报表"], 10: ["研发费用", "审计", "专项"],
    11: ["高新技术产品", "收入", "审计"], 12: ["管理", "制度", "研发", "核算"],
    13: ["研发机构", "产学研", "合作"], 14: ["激励", "转化", "奖励", "双创"],
    15: ["培养", "引进", "绩效", "培训"], 16: ["科技人员", "社保", "学历"],
    17: ["合同", "发票", "销售"], 18: ["承诺", "盖章"],
    19: ["申请书", "签字", "盖章", "高新技术企业"],
}


def get_file_size_mb(file_path):
    return round(os.path.getsize(file_path) / (1024 * 1024), 3)


def check_pdf_integrity(file_path):
    try:
        import fitz
        doc = fitz.open(str(file_path))
        page_count = len(doc)
        is_encrypted = doc.is_encrypted
        doc.close()
        if is_encrypted:
            return False, "pdf_encrypted", 0
        if page_count == 0:
            return False, "pdf_empty", 0
        return True, "ok", page_count
    except Exception as e:
        return False, f"pdf_corrupted: {e}", 0


def check_naming(filename, name_patterns):
    for pattern in name_patterns:
        if pattern.match(filename):
            return True
    if filename.lower().startswith("~$"):
        return True
    return False


def run_ocr_check(file_path, project_name):
    ocr_script = COMMON_DIR / "ocr_engine.py"
    try:
        result = subprocess.run(
            [sys.executable, str(ocr_script), "detect", "--file", str(file_path)],
            capture_output=True, text=True, timeout=300
        )
        if result.returncode != 0:
            return {"ocr_ok": False, "error": result.stderr.strip()}

        for line in reversed(result.stdout.strip().split("\n")):
            try:
                data = json.loads(line)
                if isinstance(data, dict) and "is_scanned" in data:
                    if not data.get("is_scanned"):
                        return {"ocr_ok": True, "is_scanned": False}
                    result2 = subprocess.run(
                        [sys.executable, str(ocr_script), "ocr",
                         "--file", str(file_path), "--project", project_name],
                        capture_output=True, text=True, timeout=600
                    )
                    if result2.returncode == 0:
                        for line2 in reversed(result2.stdout.strip().split("\n")):
                            try:
                                data2 = json.loads(line2)
                                if isinstance(data2, dict) and "text" in data2:
                                    return {
                                        "ocr_ok": True,
                                        "is_scanned": True,
                                        "text": data2.get("text", ""),
                                        "confidence": data2.get("confidence", 0),
                                    }
                            except json.JSONDecodeError:
                                continue
                    return {"ocr_ok": False, "is_scanned": True, "error": "OCR recognition failed"}
            except json.JSONDecodeError:
                continue
        return {"ocr_ok": True, "is_scanned": False}
    except Exception as e:
        return {"ocr_ok": False, "error": str(e)}


def verify_keywords(text, expected_kw):
    if not text:
        return False, []
    text_lower = text.lower()
    matched = [kw for kw in expected_kw if kw.lower() in text_lower]
    return len(matched) >= 1, matched


def check_ai_watermark(file_path, ocr_text=None):
    """扫描文件内容中是否包含AI生成水印

    检测两个来源：
      1. PDF文本层（fitz直接提取）
      2. OCR识别文本（如已提供）

    返回: (is_clean: bool, matched_patterns: list[str])
    """
    all_text = ""
    matched = []

    ext = Path(file_path).suffix.lower()

    if ext == ".pdf":
        try:
            import fitz
            doc = fitz.open(str(file_path))
            for page in doc:
                all_text += page.get_text()
            doc.close()
        except Exception:
            pass

    if ocr_text:
        all_text += "\n" + ocr_text

    if not all_text.strip():
        return True, []

    for pattern in AI_WATERMARK_PATTERNS:
        for m in pattern.finditer(all_text):
            matched_text = m.group(0)
            if matched_text not in matched:
                matched.append(matched_text)

    return len(matched) == 0, matched


def validate(output_dir_path, requirements_path=None):
    output_dir = Path(output_dir_path)
    if not output_dir.exists():
        return {"error": f"输出目录不存在: {output_dir}"}

    report = {
        "validate_time": datetime.now().strftime("%Y-%m-%dT%H:%M:%S"),
        "output_dir": str(output_dir),
        "checks": [],
        "summary": {"pass": 0, "warn": 0, "fail": 0, "total_files": 0, "total_size_mb": 0, "ai_watermark_hits": 0},
    }

    project_name = output_dir.parent.name

    for cat_id in range(1, 20):
        cat_name = CATEGORY_NAMES[cat_id]
        cat_dir_name = CATEGORY_DIR_NAMES.get(cat_id)
        cat_dir = output_dir / cat_dir_name
        rules = CATEGORY_RULES.get(cat_id, {})

        if not cat_dir.exists():
            report["checks"].append({
                "category": cat_id, "name": cat_name, "status": "fail",
                "issue": "目录缺失", "detail": f"未找到目录: {cat_dir_name}"
            })
            report["summary"]["fail"] += 1
            continue

        files_in_dir = [f for f in cat_dir.iterdir() if f.is_file()
                       and f.suffix.lower() not in [".json", ".md", ".xlsx", ".txt", ".tmp"]]

        if not files_in_dir:
            report["checks"].append({
                "category": cat_id, "name": cat_name, "status": "fail",
                "issue": "文件缺失", "detail": "目录存在但无上传文件"
            })
            report["summary"]["fail"] += 1
            continue

        file_results = []
        cat_fail = False
        cat_warn = False

        for f in files_in_dir:
            fc = {"file": f.name, "size_mb": get_file_size_mb(str(f))}
            report["summary"]["total_files"] += 1
            report["summary"]["total_size_mb"] += fc["size_mb"]

            ext = f.suffix.lower()
            size_mb = fc["size_mb"]
            limit_mb = rules.get("size_limit_mb", 999)
            issues = []

            if ext not in rules.get("allowed_formats", []):
                issues.append(f"格式不符: {ext}（允许: {rules['allowed_formats']}）")
                cat_fail = True

            if size_mb > limit_mb * 1.05:
                issues.append(f"文件超限: {size_mb}MB > {limit_mb}MB")
                cat_fail = True

            if ext == ".pdf":
                ok, detail, pages = check_pdf_integrity(f)
                fc["pages"] = pages
                if not ok:
                    issues.append(f"PDF异常: {detail}")
                    cat_fail = True

            name_ok = check_naming(f.name, rules.get("name_patterns", []))
            if not name_ok:
                issues.append("命名不合规")
                cat_warn = True

            ocr_result = run_ocr_check(f, project_name)
            fc["ocr"] = ocr_result
            if ocr_result.get("is_scanned") and not ocr_result.get("ocr_ok"):
                issues.append("OCR识别失败")
                cat_warn = True

            if ocr_result.get("text"):
                ok_kw, matched = verify_keywords(ocr_result["text"], EXPECTED_KEYWORDS.get(cat_id, []))
                if not ok_kw:
                    issues.append(f"内容关键词不匹配，期望: {EXPECTED_KEYWORDS.get(cat_id, [])}")
                    cat_warn = True
                else:
                    fc["content_matched_keywords"] = matched

            ai_clean, ai_matches = check_ai_watermark(f, ocr_result.get("text"))
            fc["ai_watermark_check"] = {"clean": ai_clean, "matches": ai_matches}
            if not ai_clean:
                issues.append(f"⚠ AI水印检测命中: {ai_matches}")
                cat_fail = True
                report["summary"]["ai_watermark_hits"] += 1

            fc["issues"] = issues
            fc["status"] = "fail" if any("超限" in i or "异常" in i or "格式不符" in i for i in issues) else ("warn" if issues else "pass")
            file_results.append(fc)

        if cat_fail:
            report["checks"].append({
                "category": cat_id, "name": cat_name, "status": "fail",
                "files": file_results
            })
            report["summary"]["fail"] += 1
        elif cat_warn:
            report["checks"].append({
                "category": cat_id, "name": cat_name, "status": "warn",
                "files": file_results
            })
            report["summary"]["warn"] += 1
        else:
            report["checks"].append({
                "category": cat_id, "name": cat_name, "status": "pass",
                "files": file_results
            })
            report["summary"]["pass"] += 1

    report["summary"]["total_size_mb"] = round(report["summary"]["total_size_mb"], 2)

    report_path = output_dir / "_校验报告.json"
    with open(report_path, "w", encoding="utf-8") as fp:
        json.dump(report, fp, ensure_ascii=False, indent=2)

    return report


def print_report(report):
    if "error" in report:
        print(f"[错误] {report['error']}")
        return

    s = report["summary"]
    print(f"\n{'='*70}")
    print(f"  申报材料最终校验报告")
    print(f"  时间: {report['validate_time']}")
    print(f"  目录: {report['output_dir']}")
    print(f"  {'─'*60}")
    print(f"  总文件数: {s['total_files']}  |  总大小: {s['total_size_mb']} MB")
    print(f"  ✓ 通过: {s['pass']}类  |  ⚠ 警告: {s['warn']}类  |  ✗ 失败: {s['fail']}类")
    if s.get("ai_watermark_hits", 0) > 0:
        print(f"  🚫 AI水印命中: {s['ai_watermark_hits']}个文件")
    print(f"  {'─'*60}")

    for check in report["checks"]:
        status_icon = "✓" if check["status"] == "pass" else ("⚠" if check["status"] == "warn" else "✗")
        print(f"  {status_icon} 材料{check['category']:02d} - {check['name']}")
        if check["status"] == "fail" and "issue" in check:
            print(f"      ↳ {check['issue']}: {check.get('detail', '')}")
        if "files" in check:
            for fc in check["files"]:
                if fc["status"] != "pass":
                    icon = "✗" if fc["status"] == "fail" else "⚠"
                    print(f"      {icon} {fc['file']} ({fc['size_mb']}MB)")
                    for issue in fc.get("issues", []):
                        print(f"         └ {issue}")

    print(f"{'='*70}\n")

    fail_count = s["fail"]
    ai_hits = s.get("ai_watermark_hits", 0)
    if fail_count > 0:
        print(f"⚠ 共 {fail_count} 类材料未通过校验，请修正后重新执行 pack。")
    if ai_hits > 0:
        print(f"🚫 共 {ai_hits} 个文件包含 AI 生成水印/标识，必须在交付前清除！")
        print(f"   禁止内容示例：AI生成/AI辅助/自动生成/Powered by/TRAE/GPT/Claude/大模型 等")
    if fail_count == 0 and ai_hits == 0:
        print(f"✓ 所有材料校验通过，可以上传申报系统。")


def main():
    parser = argparse.ArgumentParser(description="申报材料最终校验脚本")
    parser.add_argument("--output-dir", default="_最终申报包", help="已打包输出目录")
    parser.add_argument("--requirements", default=None, help="资料要求.xlsx路径（可选）")
    parser.add_argument("--json", action="store_true", help="仅输出JSON报告")

    args = parser.parse_args()

    report = validate(args.output_dir, args.requirements)

    if args.json:
        print(json.dumps(report, ensure_ascii=False, indent=2))
    else:
        print_report(report)

    if "error" in report:
        sys.exit(1)
    if report.get("summary", {}).get("fail", 0) > 0:
        sys.exit(1)


if __name__ == "__main__":
    main()
