"""Pixel accessory library for Jiajia desktop pet (v2).

Larger grids (24x24) so each accessory reads clearly at small sizes.
Layer codes:
  'o' = outline (dark)
  'p' = primary fill
  's' = secondary / highlight
  'd' = shadow
  'a' = accent
  'b' = bubble fill (light)
  '.' = transparent
"""

SKINS = {
    'idle': {
        'label': '待机',
        'primary':   (231, 89, 44, 255),
        'secondary': (255, 111, 56, 255),
        'shadow':    (208, 83, 41, 255),
        'outline':   (54, 53, 52, 255),
        'accent':    (255, 248, 239, 255),
        'bubble_fill': (255, 248, 239, 255),
        'bubble_outline': (54, 53, 52, 255),
        'symbol':    (54, 53, 52, 255),
    },
    'chat': {
        'label': '对话',
        'primary':   (27, 161, 193, 255),
        'secondary': (45, 178, 200, 255),
        'shadow':    (31, 59, 70, 255),
        'outline':   (15, 40, 50, 255),
        'accent':    (255, 255, 255, 255),
        'bubble_fill': (255, 255, 255, 255),
        'bubble_outline': (15, 40, 50, 255),
        'symbol':    (15, 40, 50, 255),
    },
    'think': {
        'label': '思考',
        'primary':   (155, 89, 182, 255),
        'secondary': (192, 130, 217, 255),
        'shadow':    (108, 56, 130, 255),
        'outline':   (60, 30, 75, 255),
        'accent':    (255, 248, 220, 255),
        'bubble_fill': (245, 230, 255, 255),
        'bubble_outline': (60, 30, 75, 255),
        'symbol':    (60, 30, 75, 255),
    },
    'tool': {
        'label': '工具',
        'primary':   (52, 152, 219, 255),
        'secondary': (110, 180, 230, 255),
        'shadow':    (40, 90, 130, 255),
        'outline':   (25, 50, 75, 255),
        'accent':    (255, 215, 0, 255),
        'bubble_fill': (220, 240, 255, 255),
        'bubble_outline': (25, 50, 75, 255),
        'symbol':    (25, 50, 75, 255),
    },
}


ACCESSORIES = {
    'think_bubble': {
        'title': '思考气泡',
        'desc': 'Cloud thought bubble with trailing dots',
        'w': 22, 'h': 20,
        'grid': [
            "..........oooooo.......",
            "........oobbbbbbo......",
            ".......obbbbbbbbbo.....",
            "......obbbssssbbbbo....",
            "....oobbbpsssspbbbboo..",
            "...obbbbpsssssppbbbbbo.",
            "..obbbbppssssspppbbbbbo",
            "..obbbsssppppssspbbbo..",
            ".obbbbssppppppssbbbbo..",
            ".obbbbppspppsspbbbbbo..",
            ".obbbbpppppsppbbbboo...",
            ".obbbbpppppppbbbbbo....",
            ".obbbbbpppppbbbbo......",
            ".oobbbbbppbbbboo.......",
            "...oobbbbbbbo..........",
            ".....oobbbboo..........",
            ".......oobboo..........",
            ".........oo............",
            "..........o............",
            ".......................",
        ],
        'parts': {
            'b': 'bubble_fill', 'o': 'bubble_outline',
            's': 'bubble_outline', 'p': 'symbol',
        },
    },
    'chat_bubble': {
        'title': '对话气泡',
        'desc': 'Rectangular speech bubble with a tail',
        'w': 22, 'h': 20,
        'grid': [
            ".....ooooooooooo......",
            "....obbbbbbbbbbbo.....",
            "...obbssssssssssbo....",
            "..obbspppppppppsbo....",
            "..obbspaaaaaaaapsbo...",
            "..obbspaaaaaaaapsbo...",
            "..obbspaaaaaaaapsbo...",
            "..obbspaaaaaaaapsbo...",
            "..obbspaaaaaaaapsbo...",
            "..obbspppppppppsbo....",
            "..obbssssssssssbo.....",
            "...obbbbbbbbbbbbo.....",
            "...ooobbbbbbbbbo......",
            "......ooobbbbbo.......",
            "..........oo.oo.......",
            ".........oo..oo.......",
            "........oo............",
            "......................",
            "......................",
            "......................",
        ],
        'parts': {
            'b': 'bubble_fill', 'o': 'bubble_outline',
            's': 'bubble_outline', 'p': 'primary', 'a': 'primary',
        },
    },
    'tool_icon': {
        'title': '工具图标',
        'desc': 'Wrench crossed with screwdriver',
        'w': 22, 'h': 20,
        'grid': [
            "......................",
            "............oooo.......",
            "...........opssso......",
            "..........opsssspo.....",
            "..........opssspo......",
            "..oooooo..opsspo.......",
            ".opsssspo.opspo........",
            "opsssssspoopsso........",
            ".opssssspppsso.........",
            "..opssspppsso..........",
            "...opsppsspo...........",
            "....oppsspoo...........",
            "...oppssspoo...........",
            "..opssspppoo...........",
            ".opspppoo..............",
            ".oppppo................",
            "..oppo.................",
            "...oo..................",
            "......................",
            "......................",
        ],
        'parts': {
            'o': 'outline', 'p': 'primary', 's': 'secondary', 'a': 'accent',
        },
    },
    'heart': {
        'title': '爱心',
        'desc': 'Small heart icon',
        'w': 22, 'h': 20,
        'grid': [
            "......................",
            ".....ooo.......ooo.....",
            "....oppo......oppo....",
            "...oppppo....oppppo...",
            "...opssppo..oppsspo...",
            "..oppsspppooppssppo..",
            "..oppssssppppsssspo..",
            "..oppssssppppsssspo..",
            "...oppssspppsssspo...",
            "....oppssppssspo.....",
            ".....oppspppso.......",
            "......opppppo........",
            ".......opppp.........",
            "........oppp..........",
            ".........op...........",
            "..........o...........",
            "......................",
            "......................",
            "......................",
            "......................",
        ],
        'parts': {
            'o': 'outline', 'p': 'primary', 's': 'secondary',
        },
    },
    'star': {
        'title': '星星',
        'desc': 'Five-point star',
        'w': 22, 'h': 20,
        'grid': [
            "......................",
            "...........oo..........",
            "...........oo..........",
            "..........oppo.........",
            "..........oppo.........",
            ".........oppppo........",
            "..oooooooppppppoooooo..",
            ".oppppppppppppppppppo..",
            "..oppppppppppppppppo...",
            "...oppppppppppppppo....",
            "....oppppppppppppo.....",
            ".....oppppppppppo......",
            "......oppspppspo.......",
            "......oppspppspo.......",
            ".......opsppso.........",
            "........opppo..........",
            "........oppo...........",
            ".........oo............",
            "......................",
            "......................",
        ],
        'parts': {
            'o': 'outline', 'p': 'primary', 's': 'secondary', 'a': 'accent',
        },
    },
    'zzz': {
        'title': '睡觉Z',
        'desc': 'Stacked Z symbols for sleeping state',
        'w': 22, 'h': 20,
        'grid': [
            "......................",
            ".......oooooooo.......",
            "......oobbbbbbos......",
            ".....oobbbbbbbo.......",
            "....ooobbbbboos.......",
            ".....ooobbbbbo........",
            "......ooobbbo.........",
            ".......oobbo..........",
            "........ooobbbbbboo...",
            ".......ooobbbbbbos...",
            "......ooobbbbboos.....",
            ".....ooobbbbboos......",
            "....ooobbbbboos.......",
            ".....ooobbbbbo........",
            "......ooobbbo.........",
            ".......ooobo..........",
            "........oooo..........",
            "......................",
            "......................",
            "......................",
        ],
        'parts': {
            'o': 'outline', 'b': 'accent', 's': 'primary',
        },
    },
    'note': {
        'title': '音符',
        'desc': 'Eighth note',
        'w': 22, 'h': 20,
        'grid': [
            "......................",
            "............ooo.......",
            "............opo.......",
            "............opo.......",
            "............opo.......",
            "............opo.......",
            "............opo.......",
            "............opo.......",
            "............opo.......",
            "............opo.......",
            "............opo.......",
            "...........opsso......",
            "....ooooo..opsso......",
            "...opppppssopsso......",
            "..opssppsssopso.......",
            "..opsspsssppso........",
            "...opppppsspo.........",
            "....oppppso...........",
            ".....ooooo............",
            "......................",
        ],
        'parts': {
            'o': 'outline', 'p': 'primary', 's': 'secondary',
        },
    },
    'gear': {
        'title': '齿轮',
        'desc': 'Settings gear with 8 teeth',
        'w': 22, 'h': 20,
        'grid': [
            "......................",
            "......ooo......ooo.....",
            ".....oppo......oppo....",
            ".....oppo......oppo....",
            ".oo.opppp......oppp.oo.",
            ".oppppppppoooopppppppo.",
            "..oppppppppppppppppo..",
            "..opppsssppppssssppo..",
            "..opppssssppsssssppo..",
            "..opppssssppsssssppo..",
            "..opppsssppppssssppo..",
            "..oppppppppppppppppo..",
            ".oppppppoooopppppppo..",
            ".oo.opppp......oppp.oo.",
            ".....oppo......oppo....",
            ".....oppo......oppo....",
            "......ooo......ooo.....",
            "......................",
            "......................",
            "......................",
        ],
        'parts': {
            'o': 'outline', 'p': 'primary', 's': 'secondary', 'a': 'accent',
        },
    },
}